# Generated by Django 5.2.11 on 2026-04-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sodium_mg', models.FloatField(default=0)),
                ('potassium_mg', models.FloatField(default=0)),
                ('phosphorus_mg', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('category', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='NephroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egfr', models.FloatField(blank=True, null=True, verbose_name='eGFR (ml/min/1.73m²)')),
                ('serum_creatinine', models.FloatField(blank=True, null=True, verbose_name='Serum Creatinine (mg/dL)')),
                ('blood_urea', models.FloatField(blank=True, null=True, verbose_name='Blood Urea (mg/dL)')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='BP (e.g. 120/80)')),
                ('blood_sugar', models.FloatField(blank=True, null=True, verbose_name='Blood Sugar (mg/dL)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('daily_water', models.FloatField(blank=True, null=True, verbose_name='Daily Water Intake (liters)')),
                ('notes', models.TextField(blank=True, verbose_name='Doctor Notes / Symptoms / Other Info')),
            ],
            options={
                'verbose_name_plural': 'Nephro Profiles',
            },
        ),
        migrations.CreateModel(
            name='NephroHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('egfr', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.nephroprofile')),
            ],
            options={
                'verbose_name_plural': 'Nephro Histories',
            },
        ),
    ]
