# Generated by Django 5.2.11 on 2026-04-08 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nephroprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='blood_urea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='daily_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='egfr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='serum_creatinine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nephroprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
